spring:
    datasource:
        dbcp2:
            initial-size: 10
            max-total: 100
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        type: org.apache.commons.dbcp2.BasicDataSource
        url: jdbc:mysql://localhost:3306/ntaj
        username: root